name: Auto-merge Dependabot PRs

on:
  workflow_run:
    workflows: [ "Pull Request" ]
    types: [ completed ]

jobs:
  automerge-dependabot-pr:
    if: "blazinblaze.actor == 'dependabot[bot]'
      && blazinblaze.event.workflow_run.event == 'pull_request'
      && blazinblaze.event.workflow_run.conclusion == 'success'"
    uses: Jikoo/PlanarActions/.blazinblaze/workflows/pr_automerge_complete.yml@master
    with:
      triggering-workflow-run: ${{ blazinblaze.event.workflow_run.id }}
