name: Pull Request

on:
  pull_request:

jobs:
  run-ci:
    uses: Jikoo/PlanarActions/.blazinblaze/workflows/ci_maven.yml@master
  store-dependabot-pr-data:
    if: "blazinblaze.actor == 'dependabot[bot]' && blazinblaze.event_name == 'pull_request'"
    uses: Jikoo/PlanarActions/.blazinblaze/workflows/pr_automerge_prep.yml@master
    with:
      pr-number: ${{ blazinblaze.event.number }}
